Repository SEACrowd/seacrowd-datahub, pull requests merged in 2024-05, with the labels that each got.

#602 Closes #355 | Add Dataloader TotalDefMeme
  seacrowd/sea_datasets/total_defense_meme/__init__.py
  seacrowd/sea_datasets/total_defense_meme/total_defense_meme.py
  seacrowd/utils/constants.py
  seacrowd/utils/schemas/__init__.py
  seacrowd/utils/schemas/image.py
Labels: bonus +1

#653 Closes #476 | Add/Update Dataloader OKAPI m-MMLU
  seacrowd/sea_datasets/okapi_m_mmlu/__init__.py
  seacrowd/sea_datasets/okapi_m_mmlu/okapi_m_mmlu.py
Labels: bonus +1, top-priority

#562 Closes #527 | Add Dataloader MDIA
  seacrowd/sea_datasets/mdia/__init__.py
  seacrowd/sea_datasets/mdia/mdia.py
Labels: need-fu-pr

#655 Closes #449 | Add/Update Dataloader Thai LOTUS
  seacrowd/sea_datasets/tha_lotus/__init__.py
  seacrowd/sea_datasets/tha_lotus/tha_lotus.py
Labels: bonus +1

#594 Closes #440 | Add Dataloader ASR-IBSC: AN IBAN SPEECH CORPORA
  seacrowd/sea_datasets/asr_ibsc/__init__.py
  seacrowd/sea_datasets/asr_ibsc/asr_ibsc.py
Labels: bonus +1, top-priority

#674 Closes #526 | Add dataloader for WIkiHow-GOSC
  seacrowd/sea_datasets/wikihow_gosc/__init__.py
  seacrowd/sea_datasets/wikihow_gosc/wikihow_gosc.py
Labels: source-only

#650 Closes #426 | Create dataset loader for CLIRMatrix
  seacrowd/sea_datasets/clir_matrix/__init__.py
  seacrowd/sea_datasets/clir_matrix/clir_matrix.py
Labels: source-only

#247 Closes #4 | Extend & Merge carryover ud dataloaders
  seacrowd/sea_datasets/ud/__init__.py
  seacrowd/sea_datasets/ud/ud.py
Labels: bonus +3
