Repository SEACrowd/seacrowd-datahub, pull requests merged in 2024-03, with the labels that each got.

#381 Closes #217 | Implement dataloader for `wili_2018`
  seacrowd/sea_datasets/wili_2018/__init__.py
  seacrowd/sea_datasets/wili_2018/wili_2018.py
Labels: top-priority

#409 Closes #104 | Add lazada_review_filipino
  seacrowd/sea_datasets/lazada_review_filipino/__init__.py
  seacrowd/sea_datasets/lazada_review_filipino/lazada_review_filipino.py
Labels: top-priority

#456 Closes #46 | Create dataloader for Flores200
  seacrowd/sea_datasets/flores200/__init__.py
  seacrowd/sea_datasets/flores200/flores200.py
Labels: top-priority

#471 Closes #262 | Create dataset loader for Myanmar-Rakhine Parallel
  seacrowd/sea_datasets/myanmar_rakhine_parallel/__init__.py
  seacrowd/sea_datasets/myanmar_rakhine_parallel/myanmar_rakhine_parallel.py
Labels: top-priority

#389 Closes #274 | Create OIL data loader
  seacrowd/sea_datasets/oil/__init__.py
  seacrowd/sea_datasets/oil/oil.py
Labels: source-only

#414 Closes #49 | Updated existing TICO_19 dataloader to support more sea languages
  seacrowd/sea_datasets/tico_19/tico_19.py
Labels: top-priority

#462 Closes #342 | Implement dataloader for SeaEval
  seacrowd/sea_datasets/seaeval/__init__.py
  seacrowd/sea_datasets/seaeval/seaeval.py
Labels: top-priority

#493 Closes #443 | Add dataloader for ASR-STIDUSC
  seacrowd/sea_datasets/asr_stidusc/__init__.py
  seacrowd/sea_datasets/asr_stidusc/asr_stidusc.py
Labels: top-priority

#498 Closes #32 (High Prio) | Extend XL Sum Dataloaders to SEA Langs
  seacrowd/sea_datasets/xl_sum/xl_sum.py
Labels: top-priority

#491 Closes #439 | Add dataloader for ASR-Sindodusc
  seacrowd/sea_datasets/asr_sindodusc/__init__.py
  seacrowd/sea_datasets/asr_sindodusc/asr_sindodusc.py
Labels: top-priority

#490 Closes #475 | Add dataloader for indonglish-dataset
  seacrowd/sea_datasets/indonglish/__init__.py
  seacrowd/sea_datasets/indonglish/indonglish.py
Labels: top-priority

#433 Closes #422 | Create indonesian_news_dataset dataloader
  seacrowd/sea_datasets/indonesian_news_dataset/__init__.py
  seacrowd/sea_datasets/indonesian_news_dataset/indonesian_news_dataset.py
Labels: top-priority

#463 Closes #275 | Create dataset loader for UIT-ViCoV19QA #275
  seacrowd/sea_datasets/uit_vicov19qa/__init__.py
  seacrowd/sea_datasets/uit_vicov19qa/uit_vicov19qa.py
Labels: top-priority

#492 Closes #441 | Add dataloader for ASR-SMALDUSC
  seacrowd/sea_datasets/asr_smaldusc/__init__.py
  seacrowd/sea_datasets/asr_smaldusc/asr_smaldusc.py
Labels: top-priority

#455 Closes #51 | Add id_sentiment_analysis dataloader
  seacrowd/sea_datasets/id_sentiment_analysis/__init__.py
  seacrowd/sea_datasets/id_sentiment_analysis/id_sentiment_analysis.py
Labels: top-priority

#375 Closes #188 | Implement dataloader for Sea-bench
  seacrowd/sea_datasets/sea_bench/__init__.py
  seacrowd/sea_datasets/sea_bench/sea_bench.py
Labels: top-priority

#489 Closes #115 | Create dataset loader for PhoMT dataset
  seacrowd/sea_datasets/phomt/__init__.py
  seacrowd/sea_datasets/phomt/phomt.py
Labels: top-priority

#506 Closes #267 | Add dataloader for struct_amb_ind
  seacrowd/sea_datasets/struct_amb_ind/__init__.py
  seacrowd/sea_datasets/struct_amb_ind/struct_amb_ind.py
Labels: bonus +1, top-priority

#485 Closes #347 | Create dataset loader for IndoWiki
  seacrowd/sea_datasets/indowiki/__init__.py
  seacrowd/sea_datasets/indowiki/indowiki.py
Labels: source-only

#543 Closes #446 | Add/Update Dataloader voxlingua
  seacrowd/sea_datasets/voxlingua/__init__.py
  seacrowd/sea_datasets/voxlingua/voxlingua.py
Labels: bonus +1, top-priority
