Repository SEACrowd/seacrowd-datahub, pull requests merged in 2024-04, with the labels that each got.

#500 Closes #344 | Create dataset loader for VLSP2016-SA
  seacrowd/sea_datasets/vlsp2016_sa/__init__.py
  seacrowd/sea_datasets/vlsp2016_sa/vlsp2016_sa.py
Labels: bonus +1, top-priority

#385 Closes #192 | Create dataset loader for MALINDO_parallel
  seacrowd/sea_datasets/malindo_parallel/__init__.py
  seacrowd/sea_datasets/malindo_parallel/malindo_parallel.py
Labels: top-priority

#550 Closes #12 | Add/Update Dataloader BalitaNLP
  seacrowd/sea_datasets/balita_nlp/__init__.py
  seacrowd/sea_datasets/balita_nlp/balita_nlp.py
Labels: bonus +1, pr-ready, top-priority

#509 Closes #438 | Add dataloader for ASR-INDOCSC
  seacrowd/sea_datasets/asr_indocsc/__init__.py
  seacrowd/sea_datasets/asr_indocsc/asr_indocsc.py
Labels: bonus +1, top-priority

#561 Closes #312 | Create lio_and_central_flores dataset loader
  seacrowd/sea_datasets/lio_and_central_flores/__init__.py
  seacrowd/sea_datasets/lio_and_central_flores/lio_and_central_flores.py
  seacrowd/sea_datasets/lio_and_central_flores/path_url.py
  seacrowd/sea_datasets/lio_and_central_flores/processing.py
Labels: bonus +1, top-priority

#132 Closes #109 | Add Dataloader Asian Parallel Treebank Corpus
  seacrowd/sea_datasets/parallel_asian_treebank/__init__.py
  seacrowd/sea_datasets/parallel_asian_treebank/parallel_asian_treebank.py
Labels: top-priority

#651 Update #157 | Create dataset loader for M3Exam
  seacrowd/sea_datasets/m3exam/m3exam.py
Labels: bug

#494 Closes #442 | Add dataloader for ASR-MALCSC
  seacrowd/sea_datasets/asr_malcsc/__init__.py
  seacrowd/sea_datasets/asr_malcsc/asr_malcsc.py
Labels: top-priority

#495 Closes #48 | Create dataset loader for SREDFM
  seacrowd/sea_datasets/sredfm/__init__.py
  seacrowd/sea_datasets/sredfm/sredfm.py
Labels: bonus +1

#600 Adding New Citation for beaye_lexicon
  seacrowd/sea_datasets/beaye_lexicon/beaye_lexicon.py
Labels: enhancement

#652 Closes #474 | Add Dataloader OKAPI mARC
  seacrowd/sea_datasets/okapi_m_arc/__init__.py
  seacrowd/sea_datasets/okapi_m_arc/okapi_m_arc.py
Labels: bonus +1, top-priority

#541 Closes #448 | Add/Update Dataloader alorese
  seacrowd/sea_datasets/alorese/__init__.py
  seacrowd/sea_datasets/alorese/alorese.py
  seacrowd/sea_datasets/alorese/alorese_url.py
Labels: bonus +3
